channels:
- conda-forge
dependencies:
- python =3.12
- hatchling =1.27.0
- httpcore =1.0.7
- jobflow =0.1.19
- pyiron_base =0.11.11
- pygraphviz =1.14
- aiida-workgraph =0.5.2
- conda_subprocess =0.0.6
- networkx =3.4.2
