title: Python Workflow Definition
author: Jan Janssen

execute:
  execute_notebooks           : off

repository:
    url                       : https://github.com/pyiron-dev/python-workflow-definition
    path_to_book              : ""

launch_buttons:
  notebook_interface          : jupyterlab
  binderhub_url               : https://mybinder.org