name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Conda config
      run: echo -e "channels:\n  - conda-forge\n" > .condarc
    - uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: "3.12"
        miniforge-version: latest
        condarc-file: .condarc
        environment-file: documentation/environment.yml
    - name: Install Jupyterbook
      shell: bash -l {0}
      run: |
        cp documentation/_config.yml .
        cp documentation/_toc.yml .
        cp documentation/*.md . 
        jupyter-book build . --path-output public
        mv public/_build/html public_html
        touch public_html/.nojekyll
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: public_html # The folder the action should deploy.
        CLEAN: true