name: NFDI4Ing

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: "3.12"
        environment-file: environment.yml
        auto-activate-base: false
    - name: Installation and setup
      shell: bash -l {0}
      run: |
        pip install -e qe_xml_parser
        pip install -e python_workflow_definition
        conda install -c conda-forge jupyter papermill
    - name: Create Additional Conda Environments
      shell: bash -l {0}
      run: |
        conda env create -n preprocessing -f source/envs/preprocessing.yaml -y
        conda env create -n processing -f source/envs/processing.yaml -y
        conda env create -n postprocessing -f source/envs/postprocessing.yaml -y
    - name: Tests
      shell: bash -l {0}
      run: |
        papermill pyiron_base_nfdi.ipynb pyiron_base_nfdi_out.ipynb -k "python3"
        papermill jobflow_nfdi.ipynb jobflow_nfdi_out.ipynb -k "python3"
