name: Pipeline

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: psf/black@stable
      with:
        options: "--check --diff"
        src: ./python_workflow_definition/src/python_workflow_definition
    - uses: psf/black@stable
      with:
        options: "--check --diff"
        src: ./example_workflows/quantum_espresso/qe_xml_parser/src/qe_xml_parser

  nfdi4ing:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: "3.12"
        environment-file: binder/environment.yml
        auto-activate-base: false
    - name: Installation and setup
      shell: bash -l {0}
      run: |
        pip install -e python_workflow_definition
        conda install -c conda-forge jupyter papermill
        verdi presto --profile-name pwd
        sudo apt-get install -y $(cat binder/apt.txt)
    - name: Create Additional Conda Environments
      shell: bash -l {0}
      run: |
        conda env create -n preprocessing -f example_workflows/nfdi/source/envs/preprocessing.yaml -y
        conda env create -n processing -f example_workflows/nfdi/source/envs/processing.yaml -y
        conda env create -n postprocessing -f example_workflows/nfdi/source/envs/postprocessing.yaml -y
    - name: Tests
      shell: bash -l {0}
      run: |
        cd example_workflows/nfdi/
        papermill aiida_nfdi.ipynb aiida_nfdi_out.ipynb -k "python3"
        papermill jobflow_nfdi.ipynb jobflow_nfdi_out.ipynb -k "python3"
        papermill pyiron_base_nfdi.ipynb pyiron_base_nfdi_out.ipynb -k "python3"
        papermill universal_workflow_nfdi.ipynb universal_workflow_nfdi_out.ipynb -k "python3"

  quantumespresso:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup environment
      shell: bash -l {0}
      run: tail --lines=+4 example_workflows/quantum_espresso/environment_qe.yml >> binder/environment.yml
    - uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: "3.12"
        environment-file: binder/environment.yml
        auto-activate-base: false
    - name: Installation and setup
      shell: bash -l {0}
      run: |
        pip install -e example_workflows/quantum_espresso/qe_xml_parser
        pip install -e python_workflow_definition
        conda install -c conda-forge jupyter papermill
        verdi presto --profile-name pwd
    - name: Tests
      shell: bash -l {0}
      run: |
        export ESPRESSO_PSEUDO=$(pwd)/espresso/pseudo
        cp -r example_workflows/quantum_espresso/espresso .
        cd example_workflows/quantum_espresso
        papermill aiida_qe.ipynb aiida_qe_out.ipynb -k "python3"
        papermill jobflow_qe.ipynb jobflow_qe_out.ipynb -k "python3"
        papermill pyiron_base_qe.ipynb pyiron_base_qe_out.ipynb -k "python3"
        papermill universal_workflow_qe.ipynb universal_workflow_qe_out.ipynb -k "python3"

  arithmetic:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: "3.12"
        environment-file: binder/environment.yml
        auto-activate-base: false
    - name: Installation and setup
      shell: bash -l {0}
      run: |
        pip install -e python_workflow_definition
        conda install -c conda-forge jupyter papermill
        verdi presto --profile-name pwd
    - name: Tests
      shell: bash -l {0}
      run: |
        cd example_workflows/arithmetic
        papermill aiida_arithmetic.ipynb aiida_arithmetic_out.ipynb -k "python3"
        papermill jobflow_arithmetic.ipynb jobflow_arithmetic_out.ipynb -k "python3"
        papermill pyiron_base_arithmetic.ipynb pyiron_base_arithmetic_out.ipynb -k "python3"
        papermill universal_workflow_arithmetic.ipynb universal_workflow_arithmetic_out.ipynb -k "python3"

  book:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: "3.12"
          environment-file: book/environment.yml
          auto-activate-base: false
      - name: Install Jupyterbook
        shell: bash -l {0}
        run: |
          cp book/_config.yml .
          cp book/_toc.yml .
          cp book/*.md .
          jupyter-book build . --path-output public
      - run: mv public/_build/html public_html
      - run: touch public_html/.nojekyll