name: simple

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: "3.12"
        environment-file: environment.yml
        auto-activate-base: false
    - name: Installation and setup
      shell: bash -l {0}
      run: |
        pip install -e python_workflow_definition
        conda install -c conda-forge jupyter papermill
        verdi presto --profile-name pwd
    - name: Tests
      shell: bash -l {0}
      run: |
        papermill aiida_simple.ipynb aiida_simple_out.ipynb -k "python3"
        papermill jobflow_simple.ipynb jobflow_simple_out.ipynb -k "python3"
        papermill pyiron_base_simple.ipynb pyiron_base_simple_out.ipynb -k "python3"
        papermill universal_workflow_simple.ipynb universal_workflow_simple_out.ipynb -k "python3"